# Generated by Django 5.2.6 on 2025-09-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Science', 'Science'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Other', 'Other')], max_length=100),
        ),
    ]
